package com.blog.dao;

import com.blog.model.LeaveMsg;

public interface LeaveMsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_msg
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_msg
     *
     * @mbggenerated
     */
    int insert(LeaveMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_msg
     *
     * @mbggenerated
     */
    int insertSelective(LeaveMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_msg
     *
     * @mbggenerated
     */
    LeaveMsg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_msg
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LeaveMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_msg
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LeaveMsg record);
}