package com.blog.dao;

import com.blog.model.Say;

public interface SayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table say
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table say
     *
     * @mbggenerated
     */
    int insert(Say record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table say
     *
     * @mbggenerated
     */
    int insertSelective(Say record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table say
     *
     * @mbggenerated
     */
    Say selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table say
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Say record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table say
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Say record);
}