package com.blog.dao;

import com.blog.model.UserSnapshot;

public interface UserSnapshotMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_snapshot
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_snapshot
     *
     * @mbggenerated
     */
    int insert(UserSnapshot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_snapshot
     *
     * @mbggenerated
     */
    int insertSelective(UserSnapshot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_snapshot
     *
     * @mbggenerated
     */
    UserSnapshot selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_snapshot
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserSnapshot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_snapshot
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(UserSnapshot record);
}