package com.blog.model;

import java.util.Date;

public class LeaveMsg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_msg.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_msg.receiver_id
     *
     * @mbggenerated
     */
    private Integer receiverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_msg.leaver_id
     *
     * @mbggenerated
     */
    private Integer leaverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_msg.root_id
     *
     * @mbggenerated
     */
    private Integer rootId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_msg.super_id
     *
     * @mbggenerated
     */
    private Integer superId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_msg.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_msg.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_msg.state
     *
     * @mbggenerated
     */
    private Boolean state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_msg.id
     *
     * @return the value of leave_msg.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_msg.id
     *
     * @param id the value for leave_msg.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_msg.receiver_id
     *
     * @return the value of leave_msg.receiver_id
     *
     * @mbggenerated
     */
    public Integer getReceiverId() {
        return receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_msg.receiver_id
     *
     * @param receiverId the value for leave_msg.receiver_id
     *
     * @mbggenerated
     */
    public void setReceiverId(Integer receiverId) {
        this.receiverId = receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_msg.leaver_id
     *
     * @return the value of leave_msg.leaver_id
     *
     * @mbggenerated
     */
    public Integer getLeaverId() {
        return leaverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_msg.leaver_id
     *
     * @param leaverId the value for leave_msg.leaver_id
     *
     * @mbggenerated
     */
    public void setLeaverId(Integer leaverId) {
        this.leaverId = leaverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_msg.root_id
     *
     * @return the value of leave_msg.root_id
     *
     * @mbggenerated
     */
    public Integer getRootId() {
        return rootId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_msg.root_id
     *
     * @param rootId the value for leave_msg.root_id
     *
     * @mbggenerated
     */
    public void setRootId(Integer rootId) {
        this.rootId = rootId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_msg.super_id
     *
     * @return the value of leave_msg.super_id
     *
     * @mbggenerated
     */
    public Integer getSuperId() {
        return superId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_msg.super_id
     *
     * @param superId the value for leave_msg.super_id
     *
     * @mbggenerated
     */
    public void setSuperId(Integer superId) {
        this.superId = superId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_msg.content
     *
     * @return the value of leave_msg.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_msg.content
     *
     * @param content the value for leave_msg.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_msg.create_time
     *
     * @return the value of leave_msg.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_msg.create_time
     *
     * @param createTime the value for leave_msg.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_msg.state
     *
     * @return the value of leave_msg.state
     *
     * @mbggenerated
     */
    public Boolean getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_msg.state
     *
     * @param state the value for leave_msg.state
     *
     * @mbggenerated
     */
    public void setState(Boolean state) {
        this.state = state;
    }
}