package com.blog.model;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_profile_id
     *
     * @mbggenerated
     */
    private Integer userProfileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_snapshot_id
     *
     * @mbggenerated
     */
    private Integer userSnapshotId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email_verify_code
     *
     * @mbggenerated
     */
    private String emailVerifyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email_verified
     *
     * @mbggenerated
     */
    private Boolean emailVerified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_profile_id
     *
     * @return the value of user.user_profile_id
     *
     * @mbggenerated
     */
    public Integer getUserProfileId() {
        return userProfileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_profile_id
     *
     * @param userProfileId the value for user.user_profile_id
     *
     * @mbggenerated
     */
    public void setUserProfileId(Integer userProfileId) {
        this.userProfileId = userProfileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_snapshot_id
     *
     * @return the value of user.user_snapshot_id
     *
     * @mbggenerated
     */
    public Integer getUserSnapshotId() {
        return userSnapshotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_snapshot_id
     *
     * @param userSnapshotId the value for user.user_snapshot_id
     *
     * @mbggenerated
     */
    public void setUserSnapshotId(Integer userSnapshotId) {
        this.userSnapshotId = userSnapshotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email_verify_code
     *
     * @return the value of user.email_verify_code
     *
     * @mbggenerated
     */
    public String getEmailVerifyCode() {
        return emailVerifyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email_verify_code
     *
     * @param emailVerifyCode the value for user.email_verify_code
     *
     * @mbggenerated
     */
    public void setEmailVerifyCode(String emailVerifyCode) {
        this.emailVerifyCode = emailVerifyCode == null ? null : emailVerifyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email_verified
     *
     * @return the value of user.email_verified
     *
     * @mbggenerated
     */
    public Boolean getEmailVerified() {
        return emailVerified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email_verified
     *
     * @param emailVerified the value for user.email_verified
     *
     * @mbggenerated
     */
    public void setEmailVerified(Boolean emailVerified) {
        this.emailVerified = emailVerified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.create_time
     *
     * @return the value of user.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.create_time
     *
     * @param createTime the value for user.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.update_time
     *
     * @return the value of user.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.update_time
     *
     * @param updateTime the value for user.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}