package com.blog.model;

public class UserSnapshot {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_snapshot.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_snapshot.snapshot_data
     *
     * @mbggenerated
     */
    private byte[] snapshotData;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_snapshot.id
     *
     * @return the value of user_snapshot.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_snapshot.id
     *
     * @param id the value for user_snapshot.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_snapshot.snapshot_data
     *
     * @return the value of user_snapshot.snapshot_data
     *
     * @mbggenerated
     */
    public byte[] getSnapshotData() {
        return snapshotData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_snapshot.snapshot_data
     *
     * @param snapshotData the value for user_snapshot.snapshot_data
     *
     * @mbggenerated
     */
    public void setSnapshotData(byte[] snapshotData) {
        this.snapshotData = snapshotData;
    }
}